apiVersion: v1
kind: Pod
metadata:
  name: my-volume1
spec:
  containers:
  - name: nginx
    image: shekharrr/nginx:nginx-web
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-volume
      mountPath: '/app/volume'

  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc