pipeline{
    agent {
        docker{ image 'node:16-alpine' }
    }
    stages{
        stage('BUILD'){
            steps{
                sh '''
                echo "hi"
                '''
            }
        }
        stage('DEPLOY'){
            steps{
                sh '''
                echo "hello"
                '''
            }
        }
        stage('TEST'){
            steps{
                sh '''
                echo "test"
                '''
            }
        }
    }
}