apiVersion: apps/v1
kind: Deployment
metadata:
    name: pods-node
spec: 
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
           labels: 
              app: nginx
        spec:
          nodeSelector:
            node: worker1
          containers:
              - name: nginx-2
                image: shekharrr/nginx:nginx-web
                ports:
                  - containerPort: 80 