apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-1
spec: 
    replicas: 2
        spec:
            tolerations:
                - key: "node"
                operator: "Equal"
                value: "worker2"
                effect: "NoSchedule"
           containers:
              - name: nginx-1
                image: shekharrr/nginx:nginx-web
                ports:
                  - containerPort: 80 