apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip_app-deployment
  labels:
    app: ipapp
spec:
  replicas: 3
    spec:
      containers:
      - name: ip_app
        image: shekharrr/ip_app:ip_app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
    name: ip-app-cluster-ip
spec: 
    selector:
        app: ipapp
    ports:
       - name: http
         port: 30002     
         targetPort: 80