apiVersion: apps/v1
kind: Deployment
metadata:
    name: ip-app-deployment 
spec: 
    replicas: 4
    selector:
        matchLabels:
            app: ipapp
    template:
        metadata:
           labels: 
              app: ipapp
        spec:
           containers:
              - name: ip-app 
                image: shekharrr/ip_app:ip_app
                ports:
                  - containerPort: 80 


---

apiVersion: v1
kind: Service
metadata:
    name: ip-app-cluster-ip
spec: 
    type: NodePort
    selector:
        app: ipapp
    ports:
       - name: http
         port: 30002     
         targetPort: 80
         nodePort: 30080