apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-1
spec: 
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
           labels: 
              app: nginx
        spec:
           containers:
              - name: nginx-1
                image: shekharrr/nginx:nginx-web
                ports:
                  - containerPort: 80 