apiVersion: apps/v1
kind: StatefulSet 
metadata:
    name: nginx-statefulset 
spec: 
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
           labels: 
              app: nginx-web
        spec:
           containers:
              - name: nginx
                image: shekharrr/nginx:nginx-web
                ports:
                  - containerPort: 80 

--- 

apiVersion: v1
kind: Service
metadata:
    name: nginx-headless-svc
spec: 
    clusterIP: None
    selector:
        app: nginx-web
    ports:
       - name: http
         port: 30006     
         targetPort: 80