apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs
spec:
  awsElasticBlockStore: 
    volumeID: vol-08ccaa8a5c83138a8
    fsType: xfs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi